### ISSUE TITLE
question about hydra

### ISSUE THREAD

**Issue by Senwang98** [kailiang-zhong/DESCN#3]
@kailiang-zhong 
hello, I met one env problem when using your code.
```
python main.py \
    ./conf4models/lzd_real_data/DESCN.txt \
    1 \
    ./data/real_bin_set_full.5.train.npz \
    ./data/real_bin_set_full.5.test.npz 
```
But I get the folling hydra problem, which I have speed half day but failed.
```
main.py:859: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path='./conf', config_name='conf_lzd_real_bin_v0_full.yaml')
2023-10-12 00:16:57,287 - DEBUG - Setting JobRuntime:name=UNKNOWN_NAME
2023-10-12 00:16:57,287 - DEBUG - Setting JobRuntime:name=main
Traceback (most recent call last):
  File "main.py", line 903, in <module>
    main()
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/main.py", line 99, in decorated_main
    config_name=config_name,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/utils.py", line 401, in _run_hydra
    overrides=overrides,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/utils.py", line 458, in _run_app
    lambda: hydra.run(
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    overrides=overrides,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 109, in run
    run_mode=RunMode.RUN,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 599, in compose_config
    validate_sweep_overrides=validate_sweep_overrides,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 147, in load_configuration
    validate_sweep_overrides=validate_sweep_overrides,
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 245, in _load_configuration_impl
    config_name, overrides
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 228, in _parse_overrides_and_create_caching_repo
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/dell/miniconda3/envs/pt1.12/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: LexerNoViableAltException: ./conf4models/lzd_real_data/DESCN.txt
                           ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details
```
![image](https://github.com/kailiang-zhong/DESCN/assets/23122139/7b2d4bc5-6216-4b48-a116-9a084a03daa9)

**Comment by Senwang98** [comment]
I fixed it when I use param_search.py to train, what a strange thing. Hydra-core is hard to use.

BTW, why training loss = `nan` during the training?
